// Copyright 2026 Serge Smertin
// SPDX-License-Identifier: MIT

//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"log"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

var flags = map[string]uint8{"wideGlyph": 1, "pictGlyph": 2, "emojiGlyph": 4}

// main generates glyph ranges from the Unicode data for the current Go release.
func main() {
	log.SetFlags(0)
	base := fmt.Sprintf("https://www.unicode.org/Public/%s/ucd/", unicode.Version)
	props := make([]uint8, unicode.MaxRune+1)
	for _, src := range []struct {
		url  string
		bits map[string]uint8
	}{
		{base + "EastAsianWidth.txt", map[string]uint8{"W": flags["wideGlyph"], "F": flags["wideGlyph"]}},
		{base + "emoji/emoji-data.txt", map[string]uint8{"Extended_Pictographic": flags["pictGlyph"], "Emoji": flags["emojiGlyph"]}},
	} {
		resp, err := http.Get(src.url)
		if err != nil {
			log.Fatal(err)
		}
		if resp.StatusCode != http.StatusOK {
			log.Fatalf("%s: %s", src.url, resp.Status)
		}
		sc := bufio.NewScanner(resp.Body)
		for sc.Scan() {
			line, _, _ := strings.Cut(sc.Text(), "#")
			cp, val, ok := strings.Cut(line, ";")
			bit := src.bits[strings.TrimSpace(val)]
			if !ok || bit == 0 {
				continue
			}
			lo, hi, _ := strings.Cut(strings.TrimSpace(cp), "..")
			if hi == "" {
				hi = lo
			}
			first, err := strconv.ParseInt(lo, 16, 32)
			if err != nil {
				log.Fatal(err)
			}
			last, err := strconv.ParseInt(hi, 16, 32)
			if err != nil {
				log.Fatal(err)
			}
			for r := first; r <= last; r++ {
				props[r] |= bit
			}
		}
		if err := sc.Err(); err != nil {
			log.Fatal(err)
		}
		resp.Body.Close()
	}

	fmt.Println("// Code generated by glyphs_gen.go from the Unicode Character Database. DO NOT EDIT.")
	fmt.Println()
	resp, err := http.Get("https://www.unicode.org/license.txt")
	if err != nil {
		log.Fatal(err)
	}
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("license: %s", resp.Status)
	}
	sc := bufio.NewScanner(resp.Body)
	for sc.Scan() {
		fmt.Println(strings.TrimSpace("// " + sc.Text()))
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
	resp.Body.Close()
	fmt.Println()
	fmt.Println("package tui")
	fmt.Println()
	fmt.Printf("const unicodeVersion = %q\n\n", unicode.Version)
	fmt.Println("var glyphRanges = []glyphRange{")
	for lo := 0; lo < len(props); {
		hi := lo
		for hi+1 < len(props) && props[hi+1] == props[lo] {
			hi++
		}
		if props[lo] != 0 {
			var set []string
			for name, bit := range flags {
				if props[lo]&bit != 0 {
					set = append(set, name)
				}
			}
			sort.Slice(set, func(i, j int) bool { return flags[set[i]] < flags[set[j]] })
			fmt.Printf("\t{0x%X, 0x%X, %s},\n", lo, hi, strings.Join(set, " | "))
		}
		lo = hi + 1
	}
	fmt.Println("}")
}
